##############
### EUREKA ###
##############
# eureka.client.healthcheck.enabled=true should only be set in application.yml. Setting the value in bootstrap.yml will cause undesirable side effects like registering in eureka with an UNKNOWN status.
eureka:
  client:
    healthcheck:
      enabled: false                             # 开启健康检查
  instance:
    lease-expiration-duration-in-seconds: 30    # 续约到期时间
    lease-renewal-interval-in-seconds: 10       # 续约更新时间间隔

########################################################
### EMBEDDED SERVER CONFIGURATION (ServerProperties) ###
########################################################
server:
  port: 8090
  session:
    timeout: 28800

##############
### SPRING ###
##############
spring:
  ##############
  ### Zipkin ###
  ##############
  # If using Zipkin, configure the percentage of spans exported using spring.sleuth.sampler.percentage (default 0.1, i.e. 10%). Otherwise you might think that Sleuth is not working cause it’s omitting some spans.
  # Percentage of requests that should be sampled. E.g. 1.0 - 100% requests should be sampled. The precision is whole-numbers only (i.e. there’s no support for 0.1% of the traces).
  sleuth:
    sampler:
      percentage: 1.0
  application:
    name: micro-service-wx
  aop:
    auto: true                                          # Add @EnableAspectJAutoProxy.
    proxy-target-class: false                           # Whether subclass-based (CGLIB) proxies are to be created (true) as opposed to standard Java interface-based proxies (false).
  http:
    multipart:
      enabled: true
      file-size-threshold: 0
      location:
      max-file-size: 1MB
      max-request-size: 10MB
      resolve-lazily: false
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:                                                 # 指定数据源
    initialize: false
    #schema: classpath:/sql/schema-article.sql                             # 指定数据库的建表脚本
    #data: classpath:/sql/data-article.sql                                # 指定数据库的数据脚本
    url: jdbc:mariadb://192.168.1.138:3306/mifan_wx?useUnicode=true&autoReconnect=true
    username: '{cipher}ee0f47d79c7962d74bf05e5227c7d85c8b68cba4dadc25bdf41e1a0196a4a27c'
    password: '{cipher}d2d4229be8bd6ee1b5b525aaaa379afadd194fcad6dfc75efe73bf7762574c80'
    driver-class-name: org.mariadb.jdbc.Driver
    tomcat:
      max-active: 100
      max-wait: 60000
      max-idle: 8
      min-idle: 1
      initial-size: 10
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 3000
      min-evictable-idle-time-millis: 30000
  rabbitmq:
    host: 192.168.1.138
    port: 5672
    username: '{cipher}08d2ffd2c64fd5af8ed42cae05f9427402add6c7cfdd82395b9713589128a728'
    password: '{cipher}08d2ffd2c64fd5af8ed42cae05f9427402add6c7cfdd82395b9713589128a728'
    publisher-confirms: true
    requested-heartbeat: 60
    template:
      receive-timeout: 0
      reply-timeout: 30000
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        max-interval: 10000
        multiplier: 10.0
  redis:
    host: 192.168.1.138
    port: 6379
    database: 0
    timeout: 0
    pool:
      max-active: 800
      max-wait: 60000
      max-idle: 8
      min-idle: 1

  output:
    ansi:
      enabled: always

###########################
### SECURITY PROPERTIES ###
###########################
security:
  basic:
    enabled: false
  user:
    name: '{cipher}a2596a8e905afe23feefcecd40f01dc3fa56b44c5f8891bd44d55e1f7e8c6f07'
    password: '{cipher}a2596a8e905afe23feefcecd40f01dc3fa56b44c5f8891bd44d55e1f7e8c6f07'

###############
### LOGGING ###
###############
logging:
  level:
    root: INFO
    org.hibernate: INFO                                       # 配置日志级别，让hibernate打印出执行的SQL
    org.springframework.web: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
    org.hibernate.type.descriptor.sql.BasicExtractor: INFO
    org.springframework.cloud.commons.util.InetUtils: INFO    # 开启这边的日志，可以打印出Spring查找网卡的过程

#############
### FEIGN ###
#############
feign:
  httpclient:
    connection-timeout: 10000
  hystrix:
    enabled: true

############################# To set thread isolation to SEMAPHORE,
### FEIGN HYSTRIX SUPPORT ### RequestContextHolder.getRequestAttributes() read from Thread Local, so need to set hystrix isolation strategy to SEMAPHORE
#############################
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000
    micro-service-user:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 60000
  SocketTimeout: 60000

########################
### APPLICATION CORE ###
########################
moon:
  data:
    token:
      salt: '{cipher}5227e37982548a2ba359053dc03ed4110c028d051cf136416156babac0b483c9ec3c169790e46352e0b599c6227e554dd9def7f1f7780611ae36af2ae8336797'
    elasticsearch:
      host: 192.168.1.229
  amqp:
    rabbit:
      remote-exchange: remote.direct.exchange2
      remote-queue: remote.direct.queue2
      server-data-queue: server.data.direct.queue2
      server-data-exchange: server.data.direct.exchange2
      client-data-queue: client.data.direct.queue2
      client-data-exchange: client.data.direct.exchange2
      server-event-queue: server.event.direct.queue2
      server-event-exchange: server.event.direct.exchange2
      client-event-exchange: client.event.direct.exchange2
      client-event-queue: client.event.direct.queue2
      # Spider queue
      vpn-seeds-exchange: vpn.direct.exchange4
      vpn-seeds-data-queue: vpn.data.direct.queue4
      seeds-exchange: seeds.direct.exchange4
      seeds-data-queue: seeds.data.direct.queue4
      # Text queue, Classification, Clustering
      analyzer-exchange: server.data.direct.analyzer.exchange
      analyzer-queue: server.data.direct.analyzer.queue
  jsch:
    host: 192.168.1.248
    port: 22
    user: '{cipher}3e61283a320530bdc597a3affac5a1f936bd820b55d891adafcfa89e2d17afbf'
    password: '{cipher}4886b46b986a6660a7772c8ff180beb1b81c93b1ea5db96733b6a2ad0e855e1b'
    known-hosts: 192.168.1.248 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDgkGQV57yZty+wjOdGL40+r7GBgjDHFt8q+O7KDa4lODPGZyBSnoKumsy8n4EX/mTLaGzhArWMGq2Vkxw9GxEL80kT3mrwFR1WMbHO6tzCfMGm/DiUONyP1kq9/bxTcwAUulYnVZZMdNBkSyf0T509fAB8OOjIL+2RHYmqNYU49UiFajhQLGW3BJ4scPaLdr3cq1hboKDkD53wZzDrzCXQlZmr/Fgu9FNKGGwHlBhwuEZJts94R6ACHjETLe5r5r5Ni1t/C5YL6slFNd+Tb89MxIQcO8YDD9i25V3VfnqMr2V0uW0JhWAb1hS6AQjod23yixFYN0pLP4ye0KJ4ABQH
    strict-host-key-checking: true
  model:
    mybatis:
      config-location: com/mifan/article/mybatis-config.xml
  web:
    micro-service:
      enabled: true

##########################
### APPLICATION CONFIG ###
##########################
application:
  image:
    baseUrl: http://static.budee.com/yyren/image/
  scheduler:
    enable:
      index: true
      translation: false
      update:
        timer: false
      water:
        print: false
      history:
        cache: false
  rest:
    support:
      host: 192.168.1.248
  admin:
    quartz:                           ### 是否开启后台管理的调度中心
      enable: true